version: "3.8"

services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.5.0
    container_name: mlflow_server
    ports:
      - "5000:5000"
    environment:
      MLFLOW_BACKEND_STORE_URI: sqlite:////app/mlflow.db
      MLFLOW_ARTIFACT_URI: /app/mlartifacts
    volumes:
      - ./mlflow.db:/app/mlflow.db
      - ./mlartifacts:/app/mlartifacts
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 10s
      retries: 5
      start_period: 10s

  fastapi:
    build: .
    container_name: fastapi_server
    depends_on:
      mlflow:
        condition: service_healthy  # Wait for MLflow to be ready
    ports:
      - "8000:8000"
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    command: ["uvicorn", "src.mlflow_project.api:app", "--host", "0.0.0.0", "--port", "8000"]
